### ISSUE TITLE
Criar documentação do RoadMap do produto

### ISSUE THREAD

**Issue by HianPraxedes** [fga-eps-mds/2021.2-Sigaa-Plus#105]
### Descrição:
Criando documentação do RoadMap do produto

### Tarefas:

- [x]  Decidir modelo do documento
- [x] Inserir imagem do roadmap com todas as atividades feitas até o momento

### Critérios de aceitação:

- [x] O documento deve ser revisado
- [x] O documento deve ser colocado no git

**Comment by HianPraxedes** [comment]
Documento criado e revisado.
https://github.com/fga-eps-mds/2021.2-Sigaa-Plus/blob/main/docs/DocumentoDoRoadmap.md
